### ISSUE TITLE
About CLRNet

### ISSUE THREAD

**Issue by yunhaklee** [sapirkontente/CLRmatchNet#2]
hello

I have learned a lot about the merits of your paper and think it is excellent.

in CLRNet used as the base line model, the lane prior is uniformly distributed to the initial L_0 and refined.

At this time, the refined lane prior feature map is
It seems like K1 = (x1_a, y1_a, theta1_a).

Why is K0 = (x0_a, y0_a, theta0_a) connected to K1?
What information is conveyed?

Thank you for your reply.

**Comment by sapirkontente** [comment]
Since it's related to the original CLR model, I suggest you ask its authors.
